
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Calendar;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahmad
 */
public class IBCodeGenerator extends javax.swing.JFrame {

    /**
     * Creates new form IBCodeGenerator
     */
    public IBCodeGenerator() {
        
        initComponents();
        setIcon();
        groups.removeAllItems();
        lvl.removeAllItems();
        
        sbjct.removeAllItems();
        stuff.removeAllItems();
        
        
        for (int i = 1; i <6; i++) {
            String h = "Group " + i;
            groups.addItem(h);
        }
        
        
        
        for (int year = Calendar.getInstance().get(Calendar.YEAR) -1 ; year > 1999; year--) {
            String h = year + "";
            stuff.addItem(h);
            
        }
        
        getContentPane().setBackground(Color.WHITE);
        
        field1.setVisible(false);
        field2.setVisible(false);
        
       
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        stuff = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        groups = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        sbjct = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        lvl = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        paper = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        field1 = new javax.swing.JTextField();
        field2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShanQT's IB Code Generator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generator"));

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("First one is the May test");

        jLabel7.setText("Second on is the november test");

        jButton2.setText("Google them");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stuff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuffActionPerformed(evt);
            }
        });
        jPanel2.add(stuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel1.setText("Year");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Group: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        groups.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        groups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupsActionPerformed(evt);
            }
        });
        jPanel2.add(groups, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel3.setText("Subject:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        sbjct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sbjct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbjctActionPerformed(evt);
            }
        });
        sbjct.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sbjctPropertyChange(evt);
            }
        });
        jPanel2.add(sbjct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel5.setText("Level");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        lvl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(lvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel4.setText("Paper");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));
        jPanel2.add(paper, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 61, -1));

        jButton3.setText("Something wrong? Found a bug?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int j = 2;
          String y = stuff.getSelectedItem().toString();
        String g = groups.getSelectedItem().toString();
        String s = sbjct.getSelectedItem().toString();
        String l = lvl.getSelectedItem().toString();
        
        
        if (g.equals("Group 1") || g.equals("Group 2")) {
            j = 2;
        }
        
        if (g.equals("Group 3") && l.equals("SL") ) {
            if (sbjct.equals("Business") != true) {
                j = 2;
            }
        } else if (g.equals("Group 3")){
            j = 3; 
        }
        
        
        if (paper.getText().equals("")) {
            sm.m("Please enter a value in the 'Paper' field.");
        } else if (Integer.parseInt(paper.getText()) >= j+1) {
            sm.m("Please enter a reasonable value in the 'Paper' field.");
        } else {
      
        
        String y1 = y.substring(2,3) + y.substring(3,4);
        System.out.println(y1);
        
        String g1 = g.substring(6,7);
        System.out.println(g1);
        
        String l1 = l.substring(0,1);
        String p = paper.getText();
        String s1 = "";
        switch (s){
            case "Physics":
                s1 = "PHYSI";
                break;
            case "Chemistry":
                s1 = "CHEMI";
                break;
            case "Biology":
                s1 = "BIOLO";
                break;
               
            case "ESS":
                s1 = "ENVSO";
                break;
            case "Economics":
                s1 = "ECONO";
                break;
            case "History":
                s1 = "HISTX";
                break;
            case "Geography":
                s1 = "GEOGR";
                break;
            case "Psychology":
                s1 = "PSYCH";
                break;
            case "French B":
                s1 = "ABFRE";
                break;
            case "Spanish B":
                s1 = "ABSPA";
                break;
            case "English B":
                s1 = "ABENG";
                break;
            case "English A Lit":
                s1 = "A1ENG";
                break;
            case "English A LangLit":
                s1 = "A2ENG";
                break;
            case "Business":
                s1 = "BUSMT";
                break;
            case "ITGS":
                s1 = "ITGSX";
                break;
            case "DT":
                s1 = "DESTE";
                break;
            case "Sport Science":
                s1 = "SPEXS";
           break;
            case "CS":
                s1 = "COMSC";
                
            case "Arabi B":
                s1 = "ABARA";
                
            case "Mathematics":
                if (l.equals("HL")) {
                    s1 = "MATHL";
                } else if (l.equals("SL")) {
                    s1 = "MATME";
                } else {
                    s1 = "MATSD";
                }
        }
        
        String lan = "eng";
        if (s1.equals("ABFRE") || s1.equals("ABSPA")){
            if (s1.equals("ABFRE")) {
                lan = "FRE";
            } else {
                lan = "SPA";
            }
        }
        
        if (l.equals("Ab initio")) {
            if (s1.equals("ABFRE")) {
                s1 = "ANFRE";
            } else if (s1.equals("ABSPA")) {
                s1 = "ANSPA";
            }
        }
        
        String all1 = y1 + "/" + g1 +"/" + s1 + "/" +  l1 + "P" + p + "/" + lan + "/TZ1/" + "XX";
        String all2 = y1 + "/" + g1 +"/" + s1 + "/" +  l1 + "P" + p + "/" + lan + "/TZ0/" + "XX";
        field1.setText("M" + all1);
        field1.setVisible(false);
       
        field2.setText("N" + all2);
        field2.setVisible(false);
        text.setText("M" + all1 + "\nN" + all2);
        }          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void groupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupsActionPerformed
        // TODO add your handling code here:
        sbjct.removeAllItems();
        lvl.removeAllItems();
        String m[] = new String[10];
        
        try {
        if (groups.getSelectedItem().equals("Group 1")) {
            m[0] = "English A Lit";
            m[1] = "English A LangLit";
            sm.add(m, sbjct);
            sm.may("SL", "HL", lvl);
            
           
            
        }
        if (groups.getSelectedItem().equals("Group 2")){ 
            m[0] = "French B";
            m[1] = "Spanish B";
            m[2] = "Arabic B";
            m[3] = "English B";
            sm.add(m, sbjct);
            sm.may("SL", "HL", lvl);
            lvl.addItem("Ab initio");
            
            
            
        }
        
        if (groups.getSelectedItem().equals("Group 3")) {
            m[0] = "Business";
            m[1] = "Economics";
            m[2] = "Geography";
            m[3] = "History";
            m[4] = "ITGS";
            m[5] = "Psychology";
            sm.add(m, sbjct);
            sm.may("SL","HL", lvl);
            
            
        }
        
        if (groups.getSelectedItem().equals("Group 4")) {
            m[0] = "Chemistry";
            m[1] = "Biology";
            m[2] = "DT";
            m[3] = "Physics";
            m[4] = "CS";
            m[5] = "Sport Science";
            m[6] = "ESS";
            sm.add(m, sbjct);
            sm.may("SL","HL", lvl);
        }
        
        if (groups.getSelectedItem().equals("Group 5")) {
            m[0] = "Mathematics";
            sm.add(m, sbjct);
            sm.may("SL","HL", lvl);
            lvl.addItem("Studies SL");
            
        }
        } catch (Exception e) {System.out.println("Error occured");}
    }//GEN-LAST:event_groupsActionPerformed

    private void sbjctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbjctActionPerformed
        // TODO add your handling code here:
      if (sbjct.getSelectedItem() == "Arabic B") {
            //System.out.println("Nice.");
            lvl.removeAllItems();
            sm.may("SL", "HL", lvl);
        } 
      
      if (sbjct.getSelectedItem() == "English B") {
            //System.out.println("Nice.");
            lvl.removeAllItems();
            sm.may("SL", "HL", lvl);
        } 
        if (sbjct.getSelectedItem() == "ESS") {
            //System.out.println("Nice.");
            lvl.removeAllItems();
            lvl.addItem("SL");
            
        }
        
        
    }//GEN-LAST:event_sbjctActionPerformed

    private void sbjctPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sbjctPropertyChange
        // TODO add your handling code here:
         
    }//GEN-LAST:event_sbjctPropertyChange

    private void stuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuffActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String uno = field1.getText();
        String duo = field2.getText();
        
        if (uno.equals("") || uno.equals("")) {
            sm.m("Please generate the codes");
        } else {
        //http://www.google.co.uk/search?q=
        
        try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("http://www.google.co.uk/search?q="  +uno));
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("http://www.google.co.uk/search?q=" + duo));
        }
        catch (IOException ex) 
        {
            System.out.println("Sorry man, error");
        }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Why do you think I'd give a shit? I made this in homeroom","ShanQT's IB Code Generator",JOptionPane.WARNING_MESSAGE);
        JOptionPane.showMessageDialog(null,"I'm joking, message me on facebook or email me at ahmados.dia@gmail.com","ShanQT's IB Code Generator",JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IBCodeGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IBCodeGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IBCodeGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IBCodeGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IBCodeGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field1;
    private javax.swing.JTextField field2;
    private javax.swing.JComboBox groups;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox lvl;
    private javax.swing.JTextField paper;
    private javax.swing.JComboBox sbjct;
    private javax.swing.JComboBox stuff;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
    
    try {
       // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png")));
        Toolkit.getDefaultToolkit().createImage("iconframe.png");
    } catch (Exception e) {System.out.println("Error, picture won't pictre. Goddammit otrante, wtf is this bs");}
    }

}
